In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score, auc
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import classification_report
from collections import Counter
import re
from tqdm import trange

In [5]:
pwd = 'D:/小麦/MDA-GCNFTG-main/MDA-GCNFTG-main/data/'
peco_id_name = pd.read_excel(pwd + 'peco_name.xlsx')
gene_id_name = pd.read_excel(pwd + 'gene_name.xlsx')

In [6]:
def metrics(y_true, y_pred, y_prob):

    tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()

    pos_acc = tp / sum(y_true)
    neg_acc = tn / (len(y_pred) - sum(y_pred)) # [y_true=0 & y_pred=0] / y_pred=0
    accuracy = (tp+tn)/(tn+fp+fn+tp)
    
    recall = tp / (tp+fn)
    precision = tp / (tp+fp)
    f1 = 2*precision*recall / (precision+recall)
    
    roc_auc = roc_auc_score(y_true, y_prob)
    prec, reca, _ = precision_recall_curve(y_true, y_prob)
    aupr = auc(reca, prec)
    average1 = (accuracy + precision + recall + roc_auc + aupr) / 5
    average2 = (accuracy + f1 + roc_auc + aupr) / 4
    average3 = (f1 + aupr) / 2
    print('tn = {}, fp = {}, fn = {}, tp = {}'.format(tn, fp, fn, tp))
    print('y_pred: 0 = {} | 1 = {}'.format(Counter(y_pred)[0], Counter(y_pred)[1]))
    print('y_true: 0 = {} | 1 = {}'.format(Counter(y_true)[0], Counter(y_true)[1]))
    print('acc={:.4f}|precision={:.4f}|recall={:.4f}|f1={:.4f}|auc={:.4f}|aupr={:.4f}|pos_acc={:.4f}|neg_acc={:.4f}'.format(accuracy, precision, recall, f1, roc_auc, aupr, pos_acc, neg_acc))
    print('{:.4f}, {:.4f}, {:.4f}, {:.4f}, {:.4f}, {:.4f}, {:.4f}, {:.4f}, {:.4f}'.format(accuracy, precision, recall, f1, roc_auc, aupr, average1, average2, average3))

In [25]:
def train_test_file():
    train_test_id_idx = np.load('D:/小麦/MDA-GCNFTG-main/MDA-GCNFTG-main/data/task_Tp__testlabel0_knn_edge_train_test_index_all.npz', allow_pickle = True)
    train_index_all = train_test_id_idx['train_index_all']
    test_index_all = train_test_id_idx['test_index_all']
    train_id_all = train_test_id_idx['train_id_all'] # 'gene', 'peco'
    test_id_all = train_test_id_idx['test_id_all'] # 'gene', 'peco'
    return test_index_all, test_id_all, (train_index_all, train_id_all)

In [58]:
def balanced_results_file(): #weight = None
    file = np.load("D:\小麦\MDA-GCNFTG-main\MDA-GCNFTG-main\ys.npz")
    y_true_train, y_pred_train, y_prob_train = file['arr_0'][0], file['arr_0'][1], file['arr_0'][2]
    y_true_test, y_pred_test, y_prob_test = file['arr_1'][0], file['arr_1'][1], file['arr_1'][2] 
    
    print('Train:')
    metrics(y_true_train, y_pred_train, y_prob_train)
    print('Test:')
    metrics(y_true_test, y_pred_test, y_prob_test)
    
    return y_true_test, y_pred_test, y_prob_test, (y_true_train, y_pred_train, y_prob_train)

In [112]:
df = pd.read_csv('Tp_balanced_case_study_0.csv').groupby('trait')
for name,group in df:
    a = pd.DataFrame(group)
    if a['y_true'].mean()==0 or a['y_true'].mean()==1:        
        print('**')
    else:
        print(name)
        metrics(a['y_true'], a['y_pred'], a['y_prob'])        
        print('*******************')

5-methyltryptophan exposure
tn = 204, fp = 21, fn = 2, tp = 23
y_pred: 0 = 206 | 1 = 44
y_true: 0 = 225 | 1 = 25
acc=0.9080|precision=0.5227|recall=0.9200|f1=0.6667|auc=0.9737|aupr=0.8737|pos_acc=0.9200|neg_acc=0.9903
0.9080, 0.5227, 0.9200, 0.6667, 0.9737, 0.8737, 0.8396, 0.8555, 0.7702
*******************
Magnaporthe grisea exposure
tn = 106, fp = 10, fn = 72, tp = 911
y_pred: 0 = 178 | 1 = 921
y_true: 0 = 116 | 1 = 983
acc=0.9254|precision=0.9891|recall=0.9268|f1=0.9569|auc=0.9740|aupr=0.9969|pos_acc=0.9268|neg_acc=0.5955
0.9254, 0.9891, 0.9268, 0.9569, 0.9740, 0.9969, 0.9624, 0.9633, 0.9769
*******************
Nilaparvata lugens exposure
tn = 182, fp = 29, fn = 4, tp = 12
y_pred: 0 = 186 | 1 = 41
y_true: 0 = 211 | 1 = 16
acc=0.8546|precision=0.2927|recall=0.7500|f1=0.4211|auc=0.9162|aupr=0.4719|pos_acc=0.7500|neg_acc=0.9785
0.8546, 0.2927, 0.7500, 0.4211, 0.9162, 0.4719, 0.6571, 0.6659, 0.4465
*******************
Pseudomonas avenae exposure
tn = 174, fp = 15, fn = 2, tp = 11
y_pred: 0 = 176 | 1 = 26
y_true: 0 = 189 | 1 = 13
acc=0.9158|precision=0.4231|recall=0.8462|f1=0.5641|auc=0.9597|aupr=0.6668|pos_acc=0.8462|neg_acc=0.9886
0.9158, 0.4231, 0.8462, 0.5641, 0.9597, 0.6668, 0.7623, 0.7766, 0.6155
*******************
Xanthomonas oryzae pv. oryzae exposure
tn = 175, fp = 32, fn = 8, tp = 26
y_pred: 0 = 183 | 1 = 58
y_true: 0 = 207 | 1 = 34
acc=0.8340|precision=0.4483|recall=0.7647|f1=0.5652|auc=0.8760|aupr=0.6048|pos_acc=0.7647|neg_acc=0.9563
0.8340, 0.4483, 0.7647, 0.5652, 0.8760, 0.6048, 0.7055, 0.7200, 0.5850
*******************
abscisic acid exposure
tn = 155, fp = 19, fn = 29, tp = 191
y_pred: 0 = 184 | 1 = 210
y_true: 0 = 174 | 1 = 220
acc=0.8782|precision=0.9095|recall=0.8682|f1=0.8884|auc=0.9561|aupr=0.9705|pos_acc=0.8682|neg_acc=0.8424
0.8782, 0.9095, 0.8682, 0.8884, 0.9561, 0.9705, 0.9165, 0.9233, 0.9295
*******************
aluminum nutrient exposure
tn = 183, fp = 22, fn = 0, tp = 3
y_pred: 0 = 183 | 1 = 25
y_true: 0 = 205 | 1 = 3
acc=0.8942|precision=0.1200|recall=1.0000|f1=0.2143|auc=1.0000|aupr=1.0000|pos_acc=1.0000|neg_acc=1.0000
0.8942, 0.1200, 1.0000, 0.2143, 1.0000, 1.0000, 0.8028, 0.7771, 0.6071
*******************
benzothiadiazole exposure
tn = 194, fp = 21, fn = 3, tp = 8
y_pred: 0 = 197 | 1 = 29
y_true: 0 = 215 | 1 = 11
acc=0.8938|precision=0.2759|recall=0.7273|f1=0.4000|auc=0.9362|aupr=0.5009|pos_acc=0.7273|neg_acc=0.9848
0.8938, 0.2759, 0.7273, 0.4000, 0.9362, 0.5009, 0.6668, 0.6827, 0.4505
*******************
benzyladenine exposure
tn = 195, fp = 22, fn = 0, tp = 1
y_pred: 0 = 195 | 1 = 23
y_true: 0 = 217 | 1 = 1
acc=0.8991|precision=0.0435|recall=1.0000|f1=0.0833|auc=1.0000|aupr=1.0000|pos_acc=1.0000|neg_acc=1.0000
0.8991, 0.0435, 1.0000, 0.0833, 1.0000, 1.0000, 0.7885, 0.7456, 0.5417
*******************
brassinosteroid exposure
tn = 189, fp = 20, fn = 0, tp = 5
y_pred: 0 = 189 | 1 = 25
y_true: 0 = 209 | 1 = 5
acc=0.9065|precision=0.2000|recall=1.0000|f1=0.3333|auc=1.0000|aupr=1.0000|pos_acc=1.0000|neg_acc=1.0000
0.9065, 0.2000, 1.0000, 0.3333, 1.0000, 1.0000, 0.8213, 0.8100, 0.6667
*******************
**
continuous dark (no light) exposure
tn = 166, fp = 24, fn = 36, tp = 133
y_pred: 0 = 202 | 1 = 157
y_true: 0 = 190 | 1 = 169
acc=0.8329|precision=0.8471|recall=0.7870|f1=0.8160|auc=0.9131|aupr=0.9015|pos_acc=0.7870|neg_acc=0.8218
0.8329, 0.8471, 0.7870, 0.8160, 0.9131, 0.9015, 0.8563, 0.8659, 0.8587
*******************
field study
tn = 194, fp = 35, fn = 1, tp = 9
y_pred: 0 = 195 | 1 = 44
y_true: 0 = 229 | 1 = 10
acc=0.8494|precision=0.2045|recall=0.9000|f1=0.3333|auc=0.9734|aupr=0.8450|pos_acc=0.9000|neg_acc=0.9949
0.8494, 0.2045, 0.9000, 0.3333, 0.9734, 0.8450, 0.7545, 0.7503, 0.5892
*******************
flood water exposure
tn = 185, fp = 22, fn = 0, tp = 1
y_pred: 0 = 185 | 1 = 23
y_true: 0 = 207 | 1 = 1
acc=0.8942|precision=0.0435|recall=1.0000|f1=0.0833|auc=0.9565|aupr=0.0500|pos_acc=1.0000|neg_acc=1.0000
0.8942, 0.0435, 1.0000, 0.0833, 0.9565, 0.0500, 0.5888, 0.4960, 0.0667
*******************
**
greenhouse study
tn = 194, fp = 30, fn = 2, tp = 21
y_pred: 0 = 196 | 1 = 51
y_true: 0 = 224 | 1 = 23
acc=0.8704|precision=0.4118|recall=0.9130|f1=0.5676|auc=0.9590|aupr=0.8663|pos_acc=0.9130|neg_acc=0.9898
0.8704, 0.4118, 0.9130, 0.5676, 0.9590, 0.8663, 0.8041, 0.8158, 0.7169
*******************
laboratory study
tn = 202, fp = 17, fn = 1, tp = 0
y_pred: 0 = 203 | 1 = 17
y_true: 0 = 219 | 1 = 1
acc=0.9182|precision=0.0000|recall=0.0000|f1=nan|auc=0.6119|aupr=0.0058|pos_acc=0.0000|neg_acc=0.9951
0.9182, 0.0000, 0.0000, nan, 0.6119, 0.0058, 0.3072, nan, nan
*******************
long day length exposure
tn = 169, fp = 29, fn = 15, tp = 153
y_pred: 0 = 184 | 1 = 182
y_true: 0 = 198 | 1 = 168
acc=0.8798|precision=0.8407|recall=0.9107|f1=0.8743|auc=0.9413|aupr=0.9312|pos_acc=0.9107|neg_acc=0.9185
0.8798, 0.8407, 0.9107, 0.8743, 0.9413, 0.9312, 0.9007, 0.9066, 0.9027
*******************
methyl jasmonate exposure
tn = 181, fp = 26, fn = 0, tp = 15
y_pred: 0 = 181 | 1 = 41
y_true: 0 = 207 | 1 = 15
acc=0.8829|precision=0.3659|recall=1.0000|f1=0.5357|auc=0.9800|aupr=0.7847|pos_acc=1.0000|neg_acc=1.0000
0.8829, 0.3659, 1.0000, 0.5357, 0.9800, 0.7847, 0.8027, 0.7958, 0.6602
*******************
rice yellow mottle virus exposure
tn = 188, fp = 26, fn = 5, tp = 54
y_pred: 0 = 193 | 1 = 80
y_true: 0 = 214 | 1 = 59
acc=0.8864|precision=0.6750|recall=0.9153|f1=0.7770|auc=0.9556|aupr=0.8782|pos_acc=0.9153|neg_acc=0.9741
0.8864, 0.6750, 0.9153, 0.7770, 0.9556, 0.8782, 0.8621, 0.8743, 0.8276
*******************
short day length exposure
tn = 174, fp = 24, fn = 19, tp = 88
y_pred: 0 = 193 | 1 = 112
y_true: 0 = 198 | 1 = 107
acc=0.8590|precision=0.7857|recall=0.8224|f1=0.8037|auc=0.9000|aupr=0.8399|pos_acc=0.8224|neg_acc=0.9016
0.8590, 0.7857, 0.8224, 0.8037, 0.9000, 0.8399, 0.8414, 0.8506, 0.8218
*******************
sodium chloride exposure
tn = 149, fp = 23, fn = 30, tp = 307
y_pred: 0 = 179 | 1 = 330
y_true: 0 = 172 | 1 = 337
acc=0.8959|precision=0.9303|recall=0.9110|f1=0.9205|auc=0.9560|aupr=0.9785|pos_acc=0.9110|neg_acc=0.8324
0.8959, 0.9303, 0.9110, 0.9205, 0.9560, 0.9785, 0.9343, 0.9377, 0.9495
*******************
unknown exposure
tn = 14, fp = 3, fn = 322, tp = 1800
y_pred: 0 = 336 | 1 = 1803
y_true: 0 = 17 | 1 = 2122
acc=0.8481|precision=0.9983|recall=0.8483|f1=0.9172|auc=0.9076|aupr=0.9991|pos_acc=0.8483|neg_acc=0.0417
0.8481, 0.9983, 0.8483, 0.9172, 0.9076, 0.9991, 0.9203, 0.9180, 0.9582
*******************
watering exposure
tn = 172, fp = 16, fn = 94, tp = 341
y_pred: 0 = 266 | 1 = 357
y_true: 0 = 188 | 1 = 435
acc=0.8234|precision=0.9552|recall=0.7839|f1=0.8611|auc=0.9220|aupr=0.9667|pos_acc=0.7839|neg_acc=0.6466
0.8234, 0.9552, 0.7839, 0.8611, 0.9220, 0.9667, 0.8902, 0.8933, 0.9139
*******************

<ipython-input-6-41e23ccebf3e>:11: RuntimeWarning: invalid value encountered in double_scalars
  f1 = 2*precision*recall / (precision+recall)

In [59]:
def sample(random_seed):
    all_associations = pd.read_csv('D:/小麦/MDA-GCNFTG-main/MDA-GCNFTG-main/data/all_gpe_pairs.csv', names=['gene', 'disease', 'label'])
    known_associations = all_associations.loc[all_associations['label'] == 1]
    unknown_associations = all_associations.loc[all_associations['label'] == 0]
    random_negative = unknown_associations.sample(n=known_associations.shape[0], random_state=random_seed, axis=0)

    sample_df = known_associations.append(random_negative)
    sample_df.reset_index(drop=True, inplace=True)

    return sample_df

In [78]:
def run_balanced_Tp(task, balance, knn, lr):
    test_index_all, test_id_all, _ = train_test_file()# '__nobalance'

    for i in range(1):
        print('==== Fold ', i)
        y_true_test, y_pred_test, y_prob_test, _ = balanced_results_file()

        if i == 0:
             y_true_test_all, y_pred_test_all, y_prob_test_all = y_true_test, y_pred_test, y_prob_test
            
        else:
            y_true_test_all = np.vstack([y_true_test_all, y_true_test])
            y_pred_test_all = np.vstack([y_pred_test_all, y_pred_test])
            y_prob_test_all = np.vstack([y_prob_test_all, y_prob_test])
            assert (y_prob_test_all[i] == y_prob_test).all()

    results_df = pd.DataFrame(test_id_all[0].reshape(-1, 2), columns = ['gene', 'peco'])
    print(len(results_df))
    print(len(y_true_test_all.reshape(-1)))
    results_df['y_true'] = y_true_test_all.reshape(-1)
    results_df['y_pred'] = y_pred_test_all.reshape(-1)
    results_df['y_prob'] = y_prob_test_all.reshape(-1)

    print(results_df)
    print(gene_id_name)
    results_df = pd.merge(results_df, gene_id_name, left_on = 'gene', right_index = True)
    results_df = pd.merge(results_df, peco_id_name, left_on = 'peco', right_index = True)
    #results_df.drop(labels = ['id_x', 'id_y'], axis = 1, inplace = True)
    results_df.sort_values(by = ['peco', 'y_prob'], ascending = False, inplace = True)
    
    results_df.to_csv(task + '_balanced_case_study_0.csv')
    
    return results_df

In [79]:
def run_balanced_Tgp(task, balance, knn, lr):
    dtp = sample(random_seed = 1234)
    test_index_all, test_id_all, _ = train_test_file(task, balance)# '__nobalance'

    for i in range(5):
        print('==== Fold ', i)
        y_true_test, y_pred_test, y_prob_test, _ = balanced_results_file(task, knn, lr, fold = i)

        temp = dtp.iloc[test_index_all[i]][['gene', 'peco']]
        if i == 0:
            y_true_test_all, y_pred_test_all, y_prob_test_all = y_true_test, y_pred_test, y_prob_test
            
            results_df = temp
        else:
            y_true_test_all = np.hstack([y_true_test_all, y_true_test])
            y_pred_test_all = np.hstack([y_pred_test_all, y_pred_test])
            y_prob_test_all = np.hstack([y_prob_test_all, y_prob_test])
            
            results_df = pd.concat([results_df, temp], axis = 0)
            
    results_df['y_true'] = y_true_test_all.reshape(-1)
    results_df['y_pred'] = y_pred_test_all.reshape(-1)
    results_df['y_prob'] = y_prob_test_all.reshape(-1)

    results_df = pd.merge(results_df, gene_id_name, left_on = 'gene', right_on = 'id')
    results_df = pd.merge(results_df, peco_id_name, left_on = 'peco', right_on = 'id')
    results_df.drop(labels = ['id_x', 'id_y'], axis = 1, inplace = True)
    results_df.sort_values(by = ['peco_x', 'y_prob'], ascending = False, inplace = True)
    
    results_df.to_csv(task + '_balanced_case_study_0.csv')
    
    return results_df

# Run balanced

In [80]:
results_Tp_balanced = run_balanced_Tp(task = 'Tp', balance = '', knn = '10knn', lr = 0.001)
results_Tp_balanced

==== Fold  0
Train:
tn = 1336, fp = 113, fn = 172, tp = 1250
y_pred: 0 = 1508 | 1 = 1363
y_true: 0 = 1449 | 1 = 1422
acc=0.9007|precision=0.9171|recall=0.8790|f1=0.8977|auc=0.9685|aupr=0.9699|pos_acc=0.8790|neg_acc=0.8859
0.9007, 0.9171, 0.8790, 0.8977, 0.9685, 0.9699, 0.9270, 0.9342, 0.9338
Test:
tn = 4133, fp = 533, fn = 645, tp = 4113
y_pred: 0 = 4778 | 1 = 4646
y_true: 0 = 4666 | 1 = 4758
acc=0.8750|precision=0.8853|recall=0.8644|f1=0.8747|auc=0.9428|aupr=0.9492|pos_acc=0.8644|neg_acc=0.8650
0.8750, 0.8853, 0.8644, 0.8747, 0.9428, 0.9492, 0.9033, 0.9104, 0.9120
9424
9424
       gene  peco  y_true  y_pred    y_prob
0        33     0     1.0     1.0  0.997558
1        94     0     1.0     1.0  0.998668
2        97     0     1.0     1.0  0.998778
3       155     0     1.0     1.0  0.999781
4       214     0     1.0     1.0  1.000000
...     ...   ...     ...     ...       ...
9419   4839     3     0.0     1.0  0.508719
9420   5250    19     0.0     0.0  0.109928
9421   7394    14     0.0     0.0  0.329695
9422  10270    24     0.0     0.0  0.408970
9423   3432     9     0.0     1.0  0.527762

[9424 rows x 5 columns]
                                           gene
0                                LOC_Os01g64660
1                                LOC_Os03g38000
2                                LOC_Os10g20630
3      BTH-induced ERF transcriptional factor 2
4                        Ent-kaurene synthase 6
...                                         ...
12182                            LOC_Os10g09990
12183                            LOC_Os02g38780
12184                            LOC_Os07g31130
12185                            LOC_Os11g29710
12186                            LOC_Os06g46920

[12187 rows x 1 columns]

,gene,gene_x,peco,y_true,y_pred,y_prob,gene_y,trait
7471,2020,2020,31,0.0,1.0,0.986779,LOC_Os06g20410,laboratory study
6785,5236,5236,31,0.0,1.0,0.961113,LOC_Os04g12890,laboratory study
5374,9991,9991,31,0.0,1.0,0.945579,LOC_Os05g46720,laboratory study
6716,8717,8717,31,0.0,1.0,0.943131,LOC_Os01g29409,laboratory study
6939,4814,4814,31,0.0,1.0,0.931262,LOC_Os06g22550,laboratory study
...,...,...,...,...,...,...,...,...
8885,2330,2330,0,0.0,0.0,0.000093,LOC_Os11g38860,sodium chloride exposure
7238,6070,6070,0,0.0,0.0,0.000074,LOC_Os03g24860,sodium chloride exposure
8010,6463,6463,0,0.0,0.0,0.000067,LOC_Os02g32760,sodium chloride exposure
7237,8836,8836,0,0.0,0.0,0.000035,LOC_Os04g58840,sodium chloride exposure
4856,503,503,0,0.0,0.0,0.000015,LOC_Os08g41500,sodium chloride exposure

In [10]:
# results_Tg_balanced = run_balanced_Tgp(task = 'Tg', balance = '', knn = '7knn', lr = 0.01)
# results_Tg_balanced

==== Fold  0
Train:
tn = 2283, fp = 9, fn = 16, tp = 2349
y_pred: 0 = 2299 | 1 = 2358
y_true: 0 = 2292 | 1 = 2365
acc=0.9946|precision=0.9962|recall=0.9932|f1=0.9947|auc=0.9999|aupr=0.9999|pos_acc=0.9932|neg_acc=0.9930
0.9946, 0.9962, 0.9932, 0.9947, 0.9999, 0.9999, 0.9968, 0.9973, 0.9973
Test:
tn = 1093, fp = 10, fn = 32, tp = 887
y_pred: 0 = 1125 | 1 = 897
y_true: 0 = 1103 | 1 = 919
acc=0.9792|precision=0.9889|recall=0.9652|f1=0.9769|auc=0.9941|aupr=0.9945|pos_acc=0.9652|neg_acc=0.9716
0.9792, 0.9889, 0.9652, 0.9769, 0.9941, 0.9945, 0.9844, 0.9862, 0.9857
==== Fold  1
Train:
tn = 2292, fp = 5, fn = 9, tp = 2369
y_pred: 0 = 2301 | 1 = 2374
y_true: 0 = 2297 | 1 = 2378
acc=0.9970|precision=0.9979|recall=0.9962|f1=0.9971|auc=1.0000|aupr=1.0000|pos_acc=0.9962|neg_acc=0.9961
0.9970, 0.9979, 0.9962, 0.9971, 1.0000, 1.0000, 0.9982, 0.9985, 0.9985
Test:
tn = 1097, fp = 7, fn = 72, tp = 850
y_pred: 0 = 1169 | 1 = 857
y_true: 0 = 1104 | 1 = 922
acc=0.9610|precision=0.9918|recall=0.9219|f1=0.9556|auc=0.9834|aupr=0.9851|pos_acc=0.9219|neg_acc=0.9384
0.9610, 0.9918, 0.9219, 0.9556, 0.9834, 0.9851, 0.9686, 0.9713, 0.9704
==== Fold  2
Train:
tn = 2359, fp = 6, fn = 11, tp = 2218
y_pred: 0 = 2370 | 1 = 2224
y_true: 0 = 2365 | 1 = 2229
acc=0.9963|precision=0.9973|recall=0.9951|f1=0.9962|auc=0.9999|aupr=0.9999|pos_acc=0.9951|neg_acc=0.9954
0.9963, 0.9973, 0.9951, 0.9962, 0.9999, 0.9999, 0.9977, 0.9981, 0.9981
Test:
tn = 1043, fp = 14, fn = 89, tp = 1017
y_pred: 0 = 1132 | 1 = 1031
y_true: 0 = 1057 | 1 = 1106
acc=0.9524|precision=0.9864|recall=0.9195|f1=0.9518|auc=0.9822|aupr=0.9867|pos_acc=0.9195|neg_acc=0.9214
0.9524, 0.9864, 0.9195, 0.9518, 0.9822, 0.9867, 0.9654, 0.9683, 0.9693
==== Fold  3
Train:
tn = 2342, fp = 9, fn = 6, tp = 2204
y_pred: 0 = 2348 | 1 = 2213
y_true: 0 = 2351 | 1 = 2210
acc=0.9967|precision=0.9959|recall=0.9973|f1=0.9966|auc=1.0000|aupr=1.0000|pos_acc=0.9973|neg_acc=0.9974
0.9967, 0.9959, 0.9973, 0.9966, 1.0000, 1.0000, 0.9980, 0.9983, 0.9983
Test:
tn = 1079, fp = 14, fn = 133, tp = 1103
y_pred: 0 = 1212 | 1 = 1117
y_true: 0 = 1093 | 1 = 1236
acc=0.9369|precision=0.9875|recall=0.8924|f1=0.9375|auc=0.9822|aupr=0.9867|pos_acc=0.8924|neg_acc=0.8903
0.9369, 0.9875, 0.8924, 0.9375, 0.9822, 0.9867, 0.9571, 0.9608, 0.9621
==== Fold  4
Train:
tn = 2398, fp = 0, fn = 16, tp = 2164
y_pred: 0 = 2414 | 1 = 2164
y_true: 0 = 2398 | 1 = 2180
acc=0.9965|precision=1.0000|recall=0.9927|f1=0.9963|auc=0.9998|aupr=0.9998|pos_acc=0.9927|neg_acc=0.9934
0.9965, 1.0000, 0.9927, 0.9963, 0.9998, 0.9998, 0.9977, 0.9981, 0.9980
Test:
tn = 1067, fp = 6, fn = 67, tp = 1180
y_pred: 0 = 1134 | 1 = 1186
y_true: 0 = 1073 | 1 = 1247
acc=0.9685|precision=0.9949|recall=0.9463|f1=0.9700|auc=0.9848|aupr=0.9900|pos_acc=0.9463|neg_acc=0.9409
0.9685, 0.9949, 0.9463, 0.9700, 0.9848, 0.9900, 0.9769, 0.9783, 0.9800

,miRNA_x,disease_x,y_true,y_pred,y_prob,miRNA_y,disease_y
9224,148,383,1.0,1.0,0.999978,hsa-mir-9,['Wounds and Injuries']
9226,9,383,1.0,1.0,0.999975,hsa-mir-143,['Wounds and Injuries']
9223,116,383,1.0,1.0,0.999960,hsa-mir-483,['Wounds and Injuries']
9231,10,383,1.0,1.0,0.999892,hsa-mir-145,['Wounds and Injuries']
9237,14,383,1.0,1.0,0.999791,hsa-mir-21,['Wounds and Injuries']
...,...,...,...,...,...,...,...
1402,24,1,0.0,0.0,0.000030,hsa-mir-126,"['Abortion, Habitual']"
1393,108,1,0.0,0.0,0.000026,hsa-mir-942,"['Abortion, Habitual']"
1390,164,1,0.0,0.0,0.000025,hsa-let-7i,"['Abortion, Habitual']"
1405,327,1,0.0,0.0,0.000025,hsa-mir-512,"['Abortion, Habitual']"
1391,482,1,0.0,0.0,0.000024,hsa-mir-570,"['Abortion, Habitual']"

In [12]:
results_Tpe_balanced = run_balanced_Tgp(task = 'Tpe', balance = '', knn = '5knn', lr = 0.001)
results_Tpe_balanced

==== Fold  0
Train:
tn = 2249, fp = 4, fn = 10, tp = 2162
y_pred: 0 = 2259 | 1 = 2166
y_true: 0 = 2253 | 1 = 2172
acc=0.9968|precision=0.9982|recall=0.9954|f1=0.9968|auc=1.0000|aupr=1.0000|pos_acc=0.9954|neg_acc=0.9956
0.9968, 0.9982, 0.9954, 0.9968, 1.0000, 1.0000, 0.9981, 0.9984, 0.9984
Test:
tn = 1078, fp = 12, fn = 25, tp = 1119
y_pred: 0 = 1103 | 1 = 1131
y_true: 0 = 1090 | 1 = 1144
acc=0.9834|precision=0.9894|recall=0.9781|f1=0.9837|auc=0.9974|aupr=0.9979|pos_acc=0.9781|neg_acc=0.9773
0.9834, 0.9894, 0.9781, 0.9837, 0.9974, 0.9979, 0.9893, 0.9906, 0.9908
==== Fold  1
Train:
tn = 2187, fp = 2, fn = 13, tp = 2354
y_pred: 0 = 2200 | 1 = 2356
y_true: 0 = 2189 | 1 = 2367
acc=0.9967|precision=0.9992|recall=0.9945|f1=0.9968|auc=1.0000|aupr=1.0000|pos_acc=0.9945|neg_acc=0.9941
0.9967, 0.9992, 0.9945, 0.9968, 1.0000, 1.0000, 0.9981, 0.9984, 0.9984
Test:
tn = 997, fp = 26, fn = 13, tp = 722
y_pred: 0 = 1010 | 1 = 748
y_true: 0 = 1023 | 1 = 735
acc=0.9778|precision=0.9652|recall=0.9823|f1=0.9737|auc=0.9974|aupr=0.9973|pos_acc=0.9823|neg_acc=0.9871
0.9778, 0.9652, 0.9823, 0.9737, 0.9974, 0.9973, 0.9840, 0.9866, 0.9855
==== Fold  2
Train:
tn = 2244, fp = 8, fn = 8, tp = 2076
y_pred: 0 = 2252 | 1 = 2084
y_true: 0 = 2252 | 1 = 2084
acc=0.9963|precision=0.9962|recall=0.9962|f1=0.9962|auc=1.0000|aupr=1.0000|pos_acc=0.9962|neg_acc=0.9964
0.9963, 0.9962, 0.9962, 0.9962, 1.0000, 1.0000, 0.9977, 0.9981, 0.9981
Test:
tn = 1078, fp = 14, fn = 30, tp = 1259
y_pred: 0 = 1108 | 1 = 1273
y_true: 0 = 1092 | 1 = 1289
acc=0.9815|precision=0.9890|recall=0.9767|f1=0.9828|auc=0.9972|aupr=0.9980|pos_acc=0.9767|neg_acc=0.9729
0.9815, 0.9890, 0.9767, 0.9828, 0.9972, 0.9980, 0.9885, 0.9899, 0.9904
==== Fold  3
Train:
tn = 2218, fp = 3, fn = 12, tp = 2189
y_pred: 0 = 2230 | 1 = 2192
y_true: 0 = 2221 | 1 = 2201
acc=0.9966|precision=0.9986|recall=0.9945|f1=0.9966|auc=1.0000|aupr=1.0000|pos_acc=0.9945|neg_acc=0.9946
0.9966, 0.9986, 0.9945, 0.9966, 1.0000, 1.0000, 0.9979, 0.9983, 0.9983
Test:
tn = 1085, fp = 12, fn = 24, tp = 1235
y_pred: 0 = 1109 | 1 = 1247
y_true: 0 = 1097 | 1 = 1259
acc=0.9847|precision=0.9904|recall=0.9809|f1=0.9856|auc=0.9966|aupr=0.9975|pos_acc=0.9809|neg_acc=0.9784
0.9847, 0.9904, 0.9809, 0.9856, 0.9966, 0.9975, 0.9900, 0.9911, 0.9916
==== Fold  4
Train:
tn = 2191, fp = 6, fn = 15, tp = 2229
y_pred: 0 = 2206 | 1 = 2235
y_true: 0 = 2197 | 1 = 2244
acc=0.9953|precision=0.9973|recall=0.9933|f1=0.9953|auc=0.9999|aupr=0.9999|pos_acc=0.9933|neg_acc=0.9932
0.9953, 0.9973, 0.9933, 0.9953, 0.9999, 0.9999, 0.9972, 0.9976, 0.9976
Test:
tn = 1124, fp = 4, fn = 41, tp = 962
y_pred: 0 = 1165 | 1 = 966
y_true: 0 = 1128 | 1 = 1003
acc=0.9789|precision=0.9959|recall=0.9591|f1=0.9771|auc=0.9961|aupr=0.9964|pos_acc=0.9591|neg_acc=0.9648
0.9789, 0.9959, 0.9591, 0.9771, 0.9961, 0.9964, 0.9853, 0.9871, 0.9868

,miRNA_x,disease_x,y_true,y_pred,y_prob,miRNA_y,disease_y
8048,116,383,1.0,1.0,0.999104,hsa-mir-483,['Wounds and Injuries']
8049,9,383,1.0,1.0,0.999097,hsa-mir-143,['Wounds and Injuries']
8037,148,383,1.0,1.0,0.999097,hsa-mir-9,['Wounds and Injuries']
8036,14,383,1.0,1.0,0.999079,hsa-mir-21,['Wounds and Injuries']
8034,10,383,1.0,1.0,0.998415,hsa-mir-145,['Wounds and Injuries']
...,...,...,...,...,...,...,...
8554,482,1,0.0,0.0,0.001152,hsa-mir-570,"['Abortion, Habitual']"
8543,24,1,0.0,0.0,0.001151,hsa-mir-126,"['Abortion, Habitual']"
8551,164,1,0.0,0.0,0.001149,hsa-let-7i,"['Abortion, Habitual']"
8553,454,1,0.0,0.0,0.001148,hsa-mir-767,"['Abortion, Habitual']"
8552,63,1,0.0,0.0,0.001148,hsa-mir-1246,"['Abortion, Habitual']"